apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-router
  namespace: NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kubernetes-router
  template:
    metadata:
      labels:
        app: kubernetes-router
    spec:
      serviceAccountName: kubernetes-router
      containers:
      - name: kubernetes-router
        image: IMAGE
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8077
            scheme: HTTP
          timeoutSeconds: 5
        command: ["./kubernetes-router"]
        args: ["-v", "3", "--k8s-namespace", "NAMESPACE"]
        ports:
        - containerPort: 8077
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-router
  namespace: NAMESPACE
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8077
  selector:
    app: kubernetes-router
