apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-router
subjects:
- kind: ServiceAccount
  name: kubernetes-router
  namespace: NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-router
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "secrets"
  - "events"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "nodes"
  verbs:
  - "list"
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - "customresourcedefinitions"
  verbs:
  - "get"
- apiGroups:
  - "tsuru.io"
  resources:
  - "apps"
  verbs:
  - "get"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - "ingresses"
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-router
  namespace: NAMESPACE
