version: "2"

run:
  tests: true

linters:
  enable:
    - misspell
  disable:
    - errcheck

formatters:
  enable:
    - goimports
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$